version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(deps):"
      prefix-development: "chore(deps-dev):"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
