[workspace]
members = ["singer_rust", "singer_summarize"]

[workspace.package]
version = "0.0.1-a6"
edition = "2021"
rust-version = "1.67"
repository = "https://github.com/edgarrmondragon/singer-rust"
authors = ["Edgar Ramírez <edgarrm358@gmail.com"]
